config/routes.rb
MapVotes::Application.routes.draw do
  resources :api_keys

  resources :maps do
    post 'vote', on: :member
    post 'favorite', on: :member
    post 'unfavorite', on: :member
    resources :map_comments 
  end

  resources :users do
    post 'ban', on: :member
    post 'unban', on: :member
    resources :map_favorites 
  end
  
  namespace :v1, defaults: {format: 'json'} do
    resources :api do
      post 'cast_vote', on: :collection
      post 'write_message', on: :collection
      post 'server_query', on: :collection
      post 'favorite', on: :collection
      post 'unfavorite', on: :collection
      post 'get_favorites', on: :collection
      post 'have_not_voted', on: :collection
      post 'update_map_play_time', on: :collection
    end
    
  end
  root to: "home#index"

  match "/auth/steam/callback" => "sessions#create", via: [:get, :post], as: :login
  get "/logout" => "sessions#destroy", as: :logout
end

app/models/map.rb
class Map < ActiveRecord::Base
  attr_accessible :image, :name

  has_many :map_comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :map_favorites, dependent: :destroy
  has_many :voted_by, through: :votes,
            class_name: 'User',
            source: :user

  def liked_by
    votes.likes.map(&:user)
  end
  def hated_by
    votes.hates.map(&:user)
  end

  def self.order_by_votes
    joins(:votes).select('maps.id, maps.name, sum(votes.value) as total_value').group('maps.id').order('total_value desc')
  end


  belongs_to :map_type

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  no_whitespace = /\A[\S]+\z/
  validates :name, format: {with: no_whitespace}

  before_create :type_from_prefix

  def prefix
    name.split("_", 2).first.downcase
  end

  def version
    v =name.scan(/(?:\d\d*|_(?:a|b|v|beta|erc|frc|rc|final|\d|x|z|fix|test)\d*[a-z]?)\z/).last
    unless v.nil?
      v.gsub(/\A_/, '')
    else
      nil
    end
  end

  def base_map_name
    name.sub(/\A[^_]{0,5}_/, '').sub(/_(a|b|v|beta|erc|frc|rc|final|\d|x|z|fix|test)\d*[a-z]?\z/, '')
  end

  def base_map_name_and_type
    name.sub(/_(a|b|v|beta|erc|frc|rc|final|\d|x|z|fix|test)\d*[a-z]?\z/, '')
  end

  def other_versions
    Map.search(base_map_name_and_type).flatten.uniq.reject{|m| m.name.eql?(name)}
  end

  def find_related_maps_deep
    base_map_name.split("_").select{|s| s.length>3}.map do |s|
      Map.search(s)
    end.flatten.uniq.reject{|m| m.name.eql?(name)}
  end

  def to_param
    name
  end

  def total_votes
    likes_count + hates_count
  end

  #Calculate by Wilson Confidence Curve
  def score confidence=0.95
    n = likes_count + hates_count
    if n == 0
      return 0
    end
    z = Statistics2.pnormaldist(1-(1-confidence)/2)
    phat = 1.0*likes_count/n
    (phat + z*z/(2*n) - z * Math.sqrt((phat*(1-phat)+z*z/(4*n))/n))/(1+z*z/n)
  end

  #Rate the map by how much we should play it next based on time last played and it's rating by players
  def should_play_next_score 
    (score + last_played_score) / 2
  end

  def last_played_score
    1.0 - (last_played_at.to_f / Time.now.to_f)
  end

  def self.order_by_score
    where("(likes_count > 0 OR hates_count > 0)").order("((likes_count + 1.9208) / (likes_count + hates_count) - 1.96 * SQRT((likes_count * hates_count) / (likes_count + hates_count) + 0.9604) / (likes_count + hates_count)) / (1 + 3.8416 / (likes_count + hates_count)) DESC")
  end

  def self.total_server_play_time
    sum(:total_time_played)
  end


  #Return a random map
  def self.random
    offset(rand count).first
  end

  def self.seed_from_fast_dl_site
    maplist = open ENV['FAST_DL_SITE'] do |f|
      f.read
    end.lines.to_a

    maplist.select!{|s| s.include? ".bsp.bz2"}.map! do |s|
      s.gsub(/<li>.*\"> /, "").
        gsub(/\.bsp.*$/, "").
        chomp
    end

    maplist.each do |s|
      Map.find_or_create_by_name(s)
    end
  end

  def self.search(query)
    #Use postgre text search
    if query.present?
      if Rails.configuration.database_configuration[Rails.env]["database"].eql? "postgresql"
        where("name @@ :q", q: query)
      else
        where("name like :q", q: "%#{query}%")
      end
    else
      scoped
    end
  end

  def self.filter(attributes)
    attributes.inject(self) do |scope, (key, value)|
      return scope if value.blank?
    case key.to_sym
    when :map_type_id
      scope.where(key => value)
    when :search
      scope.search(value)
    when :sort
      case value.to_sym
      when :best
        scope.order_by_score
      when :comments
        scope.where("map_comments_count > 0").order(map_comments_count: :desc)
      when :newest
        scope.order(created_at: :desc)
      when :oldest
        scope.order(created_at: :asc)
      when :last_played_at
        scope.where("total_time_played > 0").order(last_played_at: :desc)
      when :total_time_played
        scope.where("total_time_played > 0").order(total_time_played: :desc)
      else
        scope.order(:name)
      end
    else #ignore unkown keys
      scope
    end
    end

  end

  def update_play_time time_played
      self.total_time_played += time_played
      self.last_played_at = Time.now
      self.save!
  end


  private
  def type_from_prefix
    type = MapType.find_by_prefix(prefix)
    if type.nil?
      self.map_type=MapType.find_by_name("Unkown")
    else 
      self.map_type= type
    end
  end
end

app/models/map_type.rb
class MapType < ActiveRecord::Base
  has_many :maps

  validates :name, presence: true

  attr_accessible :name, :prefix
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  authorize_resource
  before_filter :find_map, only: [:show, :new, :edit, :update, :vote, :favorite, :unfavorite]

  def index
    @maps = Map.filter(params).paginate(page: params[:page], per_page: 32)
    @map_types = MapType.order(:name)
  end

  def show
    @map_comments = @map.map_comments.order(created_at: :desc)
    @other_versions = @map.other_versions
    @related = @map.find_related_maps_deep - @other_versions
  end

  def new
  end
  def edit
    @map_types = MapType.order(:name)
  end

  def update
    @map.image = params[:map][:image]
    @map.map_type_id = params[:map][:map_type_id]
    @map.origin = params[:map][:origin]
    @map.description = params[:map][:description]
    if @map.save
      redirect_to(@map)
    else
      flash[:alert] = "Could not update map"
      render action: 'edit'
    end
  end

  def vote
    value =  0
    value =  1 if params[:type] == "up"
    value = -1 if params[:type] == "down"
    Vote.cast_vote current_user, @map, value
    redirect_to :back, notice: "Thank you for voting!"
  end

  def favorite
    MapFavorite.favorite current_user, @map
    redirect_to :back, notice: "Added to favorites"
  end

  def unfavorite
    MapFavorite.unfavorite current_user, @map
    redirect_to :back, notice: "Removed from favorites"
  end

  private
  def find_map
    @map = Map.includes(:voted_by, :map_type, :map_comments).find_by(name: params[:id])
  end


end

app/helpers/maps_helper.rb
module MapsHelper
  def fast_dl_link map
    if ENV["FAST_DL_SITE"]
      File.join(ENV["FAST_DL_SITE"], ziped_file_extension(map))
    else
      ""
    end
  end

  def ziped_file_extension map
    map.name + ".bsp.bz2"
  end

  #First try provided image; than a third party source
  def smart_map_image_url map
    if url_responsive? map.image
      map.image
    else
      url = "http://image.www.gametracker.com/images/maps/160x120/tf2/#{map.name}.jpg"
      if url_responsive? url
        url
      else
        "unkown_image.jpg"
      end
    end
  end

end

app/views/maps/edit.html.erb
<h2><%= @map.name %></h2>
<%= simple_form_for @map do |f| %>
  <%= f.input :image , as: :url%>
  <%= f.input :origin, as: :url %>
  <%= f.input :map_type_id, collection: @map_types, include_blank: false %>
  <%= f.input :description, as: :text, input_html: {rows: 2, cols:50} %>
  <%= f.button :submit %>
<% end %>

app/views/maps/index.html.erb
<% provide(:title, "Map List" ) %>

<div class="row">

  <div class="col-md-8">
    <% if params[:view] == "list" || params[:view].nil? %>
      <%= render 'shared/map_quick_list', {maps: @maps} %>
    <% elsif params[:view] == "grid" %>
      <div class="grid">
        <%= render 'shared/map_image_list', {maps: @maps} %>
      </div>
    <% end %>

    <%= will_paginate @maps, renderer: BootstrapPagination::Rails %>
  </div>
  <div class="col-md-4">

    <div id="map-views" class="panel panel-default text-center">
      <div class="panel-heading">View</div>
      <div class="panel-body">
        <%= link_to_unless params[:view].blank? || params[:view] == "list",    fa_icon("list", class: "4x"), params.merge(view: "list", page: nil), {title: "List View", class: "btn btn-info"} %>
        <%= link_to_unless params[:view] == "grid", fa_icon("th", class: "4x"), params.merge(view: "grid", page: nil), {title: "Grid View", class: "btn btn-info"} %>
      </div>
    </div>

    <hr>

    <div id="map-categories" class="panel panel-default text-center">
      <div class="panel-heading">Map Categories</div>
      <div class="panel-body">
        <% @map_types.each do |map_type| %>
          <%= link_to  map_type.name, params.merge(map_type_id: map_type.id, page: nil), {class: "label label-primary"} %>
        <% end %>
      </div>
    </div>

    <hr>

    <div id="map-orders" class="panel panel-default text-center">
      <div class="panel-heading">Order By</div>
      <div class="panel-body">
        <span><%= link_to "Name", params.merge(sort: "", page: nil),{ title: "Name", class: "label label-primary"} %></span>
        <span><%= link_to "Most Popular", params.merge(sort: "best", page: nil),{ title: "Most Popular", class: "label label-primary"} %></span>
        <span><%= link_to "Most Comments", params.merge(sort: "comments", page: nil),{ title: "Most Comments", class: "label label-primary"} %></span>
        <span><%= link_to "Newest", params.merge(sort: "newest", page: nil),{ title: "Newest", class: "label label-primary"} %></span>
        <span><%= link_to "Last Played", params.merge(sort: "last_played_at", page: nil),{ title: "Last Played", class: "label label-primary"} %></span>
        <span><%= link_to "Total Time Played", params.merge(sort: "total_time_played", page: nil),{ title: "Total Time Played", class: "label label-primary"} %></span>
      </div>
    </div>


  </div>

</div>

app/views/maps/new.html.erb
<%= simple_form_for Map.new do |f| %>
  <%= f.input :name %>
  <%= f.input :image %>
  <%= f.input :map_type_id, collection: MapType.all %>
  <%= f.button :submit %>
<% end %>

app/views/maps/show.html.erb
<% provide(:title, @map.name) %>

<h2><%= @map.name %></h2>
<div class="row">
  <div class="col-md-8">
    <div class="row">
      <div class="col-md-5">
        <h4><%= @map.map_type.name %></h4>
        <% if(@map.last_played_at) %>
          <div class="last-played text-muted">
            Last played <%= time_ago_in_words(@map.last_played_at) %> ago.
          </div>
        <% end %>
        <div class="total-played text-muted">
          Played for <%= distance_of_time_in_words(@map.total_time_played) %>
        </div>
        <div>
          <%= link_to fast_dl_link(@map), {class: "btn btn-default btn-sm"} do%>
            <%= fa_icon "download", text: "Download Map", class: "fa-fw" %>
          <% end %>
        </div>

        <p class="container" id="map_description">
          <%= @map.description %>
          <div class="btn-group">
          <% unless @map.origin.empty? %>
            <span><%= link_to "Origin", @map.origin, {class: "btn btn-default btn-xs"}  %></span>
          <% end %>
          <% if can?(:update, @map) %>
            <span><%= link_to "Edit Map", edit_map_path(@map), {class: "btn btn-default btn-xs"}  %></span>
          <% end %>
          </div>
        </p>


      </div>
      <div class="col-md-3">

        <%= image_tag(smart_map_image_url(@map), class: "img-rounded map-thumbnail") %>
        <div class="btn-group">
          <%= link_to vote_map_path(@map, type: "up"), {method: "post", id: "like-it", class: "btn btn-default btn-xs up-vote"} do %>
            <%= fa_icon "thumbs-up", text: @map.likes_count, class: "fa-lg" %>
          <% end %>
          <%= link_to vote_map_path(@map, type: "down"), {method: "post", id: "hate-it", class: "btn btn-default btn-xs down-vote"} do %>
            <%= fa_icon "thumbs-down", text: @map.hates_count, class: "fa-lg" %>
          <% end %>
          <% if can?(:favorite, @map) %>
            <% if current_user.favorited? @map %>
              <%= link_to unfavorite_map_path(@map), {method: "post",id: "remove-favorite", class: "btn btn-default btn-xs "} do %>
                <%= fa_icon "star", text: "Unstar", class: "fa-lg favorite-btn" %>
              <% end %>
            <% else %>
              <%= link_to favorite_map_path(@map), {method: "post", id: "add-favorite", class: "btn btn-default btn-xs"} do %>
                <%= fa_icon "star-o", text: "Star", class: "fa-lg" %>
              <% end %>
            <% end %>
          <% end %>
        </div>

      </div>
    </div>

    <% if can?(:create, MapComment) %>
      <%= simple_form_for [@map, MapComment.new],
        method: 'post' do |f| %>
          <%= f.input :comment, as: :text, input_html: {rows: 2, cols:50} %>
          <%= f.submit "Post Comment" %>
        <% end %>
      <% else %>
        <p class="text-info">You must be logged in to leave a comment</p>
      <% end %>

      <h3>All Comments (<%= @map_comments.count %>)</h3>
      <% @map_comments.each do |mc| %>
        <div class="media" >
          <%= link_to image_tag(mc.user.avatar_url, class: "media-object"), mc.user.profile_url, class: "pull-left" %>
          <div class="media-body">
            <h4 class="media-heading"><%= link_to mc.user.nickname, mc.user.profile_url %><span class="muted"><%= mc.updated_at.to_s(:long) %></span></h4>
            <%= mc.comment %>

            <% if can?(:destroy, mc) %>
              <%= link_to "Delete", [@map, mc],  data:{confirm: "Are you sure?"}, method: :delete  %>
            <% end %>
          </div>
        </div>
      <% end %>

    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">Liked by</div>
        <div class="panel-body">
          <%= render 'shared/user_image_list', {users: @map.liked_by} %>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Hated by</div>
        <div class="panel-body">
          <%= render 'shared/user_image_list', {users: @map.hated_by} %>
        </div>
      </div>
    </div>

  </div>

  <% if @related.length > 0 %>
  <h3>Related Maps</h3>
  <%= render 'shared/map_image_list', {maps: @related} %>
  <% end %>
  <% if @other_versions.length > 0 %>
  <h3>Other Versions</h3>
  <%= render 'shared/map_image_list', {maps: @other_versions} %>
  <% end %>