config/routes.rb
MapVotes::Application.routes.draw do
  resources :api_keys

  resources :maps do
    post 'vote', on: :member
    post 'favorite', on: :member
    post 'unfavorite', on: :member
    resources :map_comments 
  end

  resources :users do
    post 'ban', on: :member
    post 'unban', on: :member
    resources :map_favorites 
  end
  
  namespace :v1, defaults: {format: 'json'} do
    resources :api do
      post 'cast_vote', on: :collection
      post 'write_message', on: :collection
      post 'server_query', on: :collection
      post 'favorite', on: :collection
      post 'unfavorite', on: :collection
      post 'get_favorites', on: :collection
      post 'have_not_voted', on: :collection
      post 'update_map_play_time', on: :collection
    end
    
  end
  root to: "home#index"

  match "/auth/steam/callback" => "sessions#create", via: [:get, :post], as: :login
  get "/logout" => "sessions#destroy", as: :logout
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Map Votes", root_path, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse">
          <ul class ="nav navbar-nav">
            <li>
              <%= simple_form_for :map, url: maps_path, method: "get", html: { class: "navbar-form navbar-left", role: "search"} do |f| %>
              <div class="form-group">
                <%= f.input_field :search, name: "search", class: "form-control" , placeholder: "Search Maps", value: params[:search] %>
              </div>
              <%= f.submit "Search", class: "btn btn-success" %>
              <% end %>
            </li>
            <%= navbar_list_item "Map List", maps_path %>
            <%= navbar_list_item "Add Map", new_map_path, can?(:create, Map) %>
            <%= navbar_list_item "Add API Key", api_keys_path, can?(:read, ApiKey) %>
            <%= navbar_list_item "Account Info", user_path(current_user), can?(:read, current_user) %>
            <% if current_user %>
              <%= navbar_list_item "Log Out", logout_path %>
              <%= navbar_list_item image_tag(current_user.avatar_icon_url, alt: "avatar"), current_user.profile_url %>
            <%else %>
              <%= navbar_list_item image_tag("sits_small.png", alt: "Sign in with Steam"), "/auth/steam" %>
            <% end %>
          </ul>


        </div>
      </div>
    </div>

    <%= render partial: "shared/flash_messages", flash: flash %>

    <div class="container" >
      <%= yield %>
    </div>

    <footer >
      <div class="row">
        <div class="col-md-3">
          <%= link_to "Powered By Steam", "http://steampowered.com" %>
        </div>
      </div>
    </div>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>